"""M5 test fixtures: a disposable PostgreSQL database per test session, migrated with Alembic,
loaded with the SYNTHETIC M1 fixture (ml/tests/fixture_data.py) and a SYNTHETIC M3 bundle
(ml/tests/m3_fixture.py). No real data is used here.

Set TWIN_TEST_DATABASE_URL to a server you may create databases on, e.g.
  postgresql+psycopg://postgres:postgres@127.0.0.1:5432/postgres     (docker compose: make db-up)
Without it, every database test is skipped (reported as skipped, never silently passed).
"""

from __future__ import annotations

import os
import shutil
import sys
import uuid
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "ml/tests"))
sys.path.insert(0, str(Path(__file__).parent))
from api_support import PASSWORDS, SOURCE_LABEL, alembic_config, login  # noqa: E402

ADMIN_URL = os.environ.get("TWIN_TEST_DATABASE_URL")


def need_db() -> str:
    if not ADMIN_URL:
        pytest.skip("TWIN_TEST_DATABASE_URL not set: PostgreSQL tests skipped")
    return ADMIN_URL


class TempDatabase:
    def __init__(self, admin_url: str) -> None:
        from sqlalchemy import create_engine

        self.name = f"twin_test_{uuid.uuid4().hex[:10]}"
        self.admin = create_engine(admin_url, isolation_level="AUTOCOMMIT")
        with self.admin.connect() as c:
            c.exec_driver_sql(f'CREATE DATABASE "{self.name}"')
        self.url = admin_url.rsplit("/", 1)[0] + "/" + self.name

    def drop(self) -> None:
        with self.admin.connect() as c:
            c.exec_driver_sql(f'DROP DATABASE IF EXISTS "{self.name}" WITH (FORCE)')
        self.admin.dispose()


@pytest.fixture
def empty_db() -> Iterator[str]:
    db = TempDatabase(need_db())
    yield db.url
    db.drop()


@pytest.fixture(scope="session")
def db_url() -> Iterator[str]:
    from alembic import command

    db = TempDatabase(need_db())
    command.upgrade(alembic_config(db.url), "head")
    yield db.url
    db.drop()


@pytest.fixture(scope="session")
def engine(db_url: str) -> Iterator[Any]:
    from twin_api.db import make_engine

    e = make_engine(db_url)
    yield e
    e.dispose()


@pytest.fixture(scope="session")
def configs() -> Any:
    from twin_core.twin import TwinConfigs

    return TwinConfigs.load(REPO / "data/configs")


@pytest.fixture(scope="session")
def m1(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Any]:
    from fixture_data import write_fixture
    from twin_ml.dataset.run import run_m2
    from twin_ml.pipeline.run import run_m1

    src = write_fixture(tmp_path_factory.mktemp("src"))
    root = tmp_path_factory.mktemp("repo")
    (root / "data").mkdir()
    shutil.copytree(REPO / "data/configs", root / "data/configs")
    (root / "docs").mkdir()
    (root / "docs/data-card.md").write_text(
        "x\n<!-- AUTO:M1-AUDIT START (generated by `make m1`; do not edit by hand) -->\n"
        "<!-- AUTO:M1-AUDIT END -->\n"
    )
    r1 = run_m1(src, root, write_outputs=False)
    r2 = run_m2(r1.tables, root, write_outputs=False)
    return {
        "tables": r1.tables,
        "m1_manifest": r1.run_manifest,
        "m2_manifest": r2.run_manifest,
        "dataset": r2.dataset,
    }


@pytest.fixture(scope="session")
def bundle(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Any]:
    from m3_fixture import FIXTURE_LABEL, make_m2_like, pin_folds
    from twin_ml.pipeline.run import content_sha256
    from twin_ml.training.bundle import save_bundle
    from twin_ml.training.run import run_m3

    data = make_m2_like()
    root = tmp_path_factory.mktemp("m3")
    shutil.copytree(REPO / "data/configs", root / "data/configs")
    pin_folds(data, root)
    res = run_m3(
        data,
        root,
        write_outputs=False,
        dataset_label=FIXTURE_LABEL,
        require_xgboost=False,
        overrides={
            "primary_model": "logistic",
            "evaluation": {"bootstrap_resamples": 10, "ci": 0.95, "calibration_bins": 5},
        },
    )
    b = res.bundles["logistic__full_personal"]
    path = root / "logistic__full_personal.joblib"
    save_bundle(b, path)
    return {"bundle": b, "path": path, "train_data": data, "train_sha": content_sha256(data)}


@pytest.fixture(scope="session")
def loaded(engine: Any, m1: dict[str, Any], bundle: dict[str, Any], configs: Any) -> dict[str, Any]:
    from twin_api.auth import create_user
    from twin_api.db import make_sessionmaker, session_scope
    from twin_api.ingest import ingest_tables
    from twin_api.registry import activate, register_bundle, store_support_profile

    res = ingest_tables(
        engine,
        m1["tables"],
        source_dir="fixture",
        source_label=SOURCE_LABEL,
        m1_manifest=m1["m1_manifest"],
        m2_manifest=m1["m2_manifest"],
        features_sha256=configs.hashes["features"],
        labels_version=configs.labels.version,
    )
    factory = make_sessionmaker(engine)
    with session_scope(factory) as s:
        sp = store_support_profile(s, bundle["train_data"], bundle["train_sha"], configs)
        mv = register_bundle(s, bundle["path"], configs, registered_by="tests")
        activate(s, mv.id, configs)
        for role, pw in PASSWORDS.items():
            create_user(s, role, pw, role)
        ids = {"model_version_id": mv.id, "support_profile_id": sp.id}
    return {"ingest": res, **ids}


@pytest.fixture(scope="session")
def app(db_url: str, loaded: dict[str, Any]) -> Any:
    from twin_api.app import create_app
    from twin_api.settings import Settings

    settings = Settings(
        database_url=db_url, environment="test", cookie_secure=False, source_label=SOURCE_LABEL
    )
    return create_app(settings)


@pytest.fixture
def client(app: Any) -> Iterator[Any]:
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        yield c


def _as(app: Any, role: str) -> Iterator[tuple[Any, dict[str, str]]]:
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        yield c, {"X-CSRF-Token": login(c, role)}


@pytest.fixture
def clinician(app: Any) -> Iterator[tuple[Any, dict[str, str]]]:
    yield from _as(app, "clinician")


@pytest.fixture
def admin(app: Any) -> Iterator[tuple[Any, dict[str, str]]]:
    yield from _as(app, "admin")
