"""Markdown rendering of the M3 evaluation report."""

from __future__ import annotations

import math
from typing import Any


def clean(obj: Any) -> Any:
    """NaN/inf -> None so the JSON report is valid JSON."""
    if isinstance(obj, float) and not math.isfinite(obj):
        return None
    if isinstance(obj, dict):
        return {k: clean(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [clean(v) for v in obj]
    return obj


def _n(v: Any, digits: int = 3) -> str:
    return (
        "–" if v is None or (isinstance(v, float) and not math.isfinite(v)) else f"{v:.{digits}f}"
    )


def _ci(pop: dict[str, Any], metric: str) -> str:
    if "pooled" not in pop:
        return "–"
    ci = pop["bootstrap_ci"][metric]
    return f"{_n(pop['pooled'][metric])} [{_n(ci['lo'])}, {_n(ci['hi'])}]"


def _metrics_table(runs: dict[str, Any], population: str) -> list[str]:
    lines = [
        "| Run | Columns | Meals (pos.) | AUROC [95% CI] | PR-AUC [95% CI] | Prevalence | Brier [95% CI] | Cal. slope | ECE |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for rid, r in runs.items():
        pop = r[population]
        if "pooled" not in pop:
            lines.append(f"| {rid} | {r['n_columns']} | 0 | – | – | – | – | – | – |")
            continue
        p = pop["pooled"]
        lines.append(
            f"| {rid} | {r['n_columns']} | {p['meals']} ({p['positives']}) | {_ci(pop, 'auroc')} | "
            f"{_ci(pop, 'pr_auc')} | {_n(p['prevalence'])} | {_ci(pop, 'brier')} | "
            f"{_n(p['calibration_slope'], 2)} | {_n(p['ece'])} |"
        )
    return lines


def report_markdown(r: dict[str, Any]) -> str:
    runs = r["runs"]
    c = r["counts"]
    primary = r["primary"]["run"]
    lines = [
        "# M3 evaluation report",
        "",
        f"**Data: {r['dataset_label']}** (dataset content `{r['dataset_content_sha256'][:12]}`)",
        "",
        "Generated by `make m3`. Every number below is an out-of-fold (OOF) result: each meal was "
        "predicted by a model whose training, tuning, calibration, threshold and personalization "
        "prior never saw that participant (nested participant-level CV on the pinned folds).",
        "",
        f"- Eligible meals: {c['eligible_meals']}. Target group (prediabetes + T2D): "
        f"{c['eligible_target_meals']} meals, {c['eligible_target_positives']} positive, "
        f"{c['target_participants']} participants. Healthy: {c['eligible_healthy_meals']} meals, "
        f"{c['eligible_healthy_positives']} positive, {c['healthy_participants']} participants.",
        f"- Primary pre-registered result: **{primary}**, {r['primary']['metric']}"
        + ("" if r["primary"]["ran"] else " — **NOT RUN** (model unavailable)"),
        f"- XGBoost available: {r['xgboost_available']}. Runtime: {r['runtime_seconds']} s.",
        "",
        "## Target group (primary population), pooled OOF",
        "",
        *_metrics_table(runs, "target"),
        "",
        "PR-AUC must be read against the prevalence (a random model's PR-AUC). Brier: lower is better. "
        "Calibration slope: 1 is ideal; below 1 means predictions are too extreme.",
        "",
        "## Healthy participants (reported separately, not the primary population)",
        "",
        *_metrics_table(runs, "healthy"),
        "",
        "## Pre-registered comparisons (target group, paired participant bootstrap)",
        "",
        "| Comparison | A | B | ΔPR-AUC [95% CI] | ΔAUROC [95% CI] | Share of resamples A not better (PR-AUC) |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for cmp in r["comparisons"]:
        if not cmp["ran"]:
            lines.append(f"| {cmp['comparison']} | {cmp['a']} | {cmp['b']} | not run | not run | |")
            continue
        pa, au = cmp["pr_auc"], cmp["auroc"]
        lines.append(
            f"| {cmp['comparison']} | {cmp['a']} | {cmp['b']} | {_n(pa['difference'])} "
            f"[{_n(pa['lo'])}, {_n(pa['hi'])}] | {_n(au['difference'])} [{_n(au['lo'])}, "
            f"{_n(au['hi'])}] | {_n(pa['share_resamples_a_not_better'])} |"
        )
    if primary in runs:
        pr = runs[primary]["target"]
        lines += [
            "",
            f"## Primary run per fold ({primary}, target group)",
            "",
            "| Fold | Participants | Meals (pos.) | AUROC | PR-AUC | Brier | Threshold |",
            "| --- | --- | --- | --- | --- | --- | --- |",
            *[
                f"| {f['fold']} | {f['participants']} | {f['meals']} ({f['positives']}) | "
                f"{_n(f['auroc'])} | {_n(f['pr_auc'])} | {_n(f['brier'])} | {_n(f['threshold'])} |"
                for f in pr.get("per_fold", [])
            ],
            "",
            "### Calibration curve (quantile bins)",
            "",
            "| Bin | Meals | Mean predicted | Observed rate |",
            "| --- | --- | --- | --- |",
            *[
                f"| {b['bin']} | {b['n']} | {_n(b['mean_predicted'])} | {_n(b['observed_rate'])} |"
                for b in pr.get("calibration_curve", [])
            ],
            "",
            "### At the threshold chosen on inner folds",
            "",
            "| Sensitivity | Specificity | PPV | NPV | F1 | Share flagged |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        tm = pr.get("at_threshold", {})
        lines.append(
            f"| {_n(tm.get('sensitivity'))} | {_n(tm.get('specificity'))} | {_n(tm.get('ppv'))} | "
            f"{_n(tm.get('npv'))} | {_n(tm.get('f1'))} | {_n(tm.get('flagged_share'))} |"
        )
    if r["shap"]:
        lines += [
            "",
            f"## SHAP ({r['shap']['run']}, OOF meals only, {r['shap']['scale']})",
            "",
            "| Rank | Feature | Mean abs SHAP (target group) |",
            "| --- | --- | --- |",
            *[
                f"| {i + 1} | {d['feature']} | {_n(d['mean_abs_shap'], 4)} |"
                for i, d in enumerate(r["shap"]["global_importance_target"][:15])
            ],
            "",
            "SHAP shows what the model relies on. It is association, not cause: it does not say that "
            "changing a feature would change glucose.",
        ]
    lines += [
        "",
        "## Leakage and fitting boundaries",
        "",
        f"- {r['leakage']['model_inputs']}",
        f"- {r['leakage']['oof_coverage']}",
        "- Audit-log checks passed for every run (fits recorded per stage): "
        + ", ".join(f"{k}: {v}" for k, v in list(r["leakage"]["nested_cv_boundaries"].items())[:1])
        + f" (and {max(len(r['leakage']['nested_cv_boundaries']) - 1, 0)} more runs)",
        "",
        "## Limitations",
        "",
        "- 44 participants in total (about 30 in the target group): intervals are wide, and one "
        "fold holds only a handful of target participants.",
        "- Regime A only (new participants). The temporal regime (B) is P1.",
        "- Labels use the frozen 1-minute Dexcom series, features native readings (ADR-013); "
        "SA-1 is registered as P2.",
        "- Associations only: nothing here is a causal effect of any feature.",
    ]
    return "\n".join(lines) + "\n"
