"""Render the audit as JSON (machine-readable), Markdown (human-readable) and the data-card block."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

AUTO_START = "<!-- AUTO:M1-AUDIT START (generated by `make m1`; do not edit by hand) -->"
AUTO_END = "<!-- AUTO:M1-AUDIT END -->"


def dumps(obj: Any) -> str:
    return json.dumps(obj, indent=2, sort_keys=True, default=str) + "\n"


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    def fmt(v: Any) -> str:
        return "" if v is None else str(v).replace("|", "\\|")

    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    lines += ["| " + " | ".join(fmt(v) for v in r) + " |" for r in rows]
    return "\n".join(lines)


def _pct(v: float | None) -> str:
    return "" if v is None else f"{v * 100:.1f}%"


def summary_markdown(audit: dict[str, Any]) -> str:
    """The compact block embedded in docs/data-card.md."""
    p, o = audit["participants"], audit["outcomes"]
    tf, te = o["target_frozen"], o["target_eligible"]
    nd = audit["native_cgm"]["dexcom"]
    lines = [
        f"- Source check: {audit['provenance']['official_check']['status']} (official), "
        f"{audit['provenance']['lock_check']['status']} (pinned manifest "
        f"`{audit['provenance']['manifest_sha256'][:12]}`)",
        f"- Time-series files: **{p['timeseries_files']}**; bio.csv rows: {p['bio_rows']}; "
        f"absent IDs in 1–{max(p['timeseries_ids'])}: {p['ids_absent_between_1_and_max']}; "
        f"clinical record without time series: {p['bio_without_timeseries']}",
        f"- Groups with time series: {p['groups_with_timeseries']}",
        f"- Meal rows: {audit['meals']['meal_rows']} ({audit['meals']['by_type']}); macro validity "
        f"{audit['meals']['macro_validity']}",
        f"- Dexcom native grid: {nd['decisions']}; {nd['native_readings']} native readings of "
        f"{nd['values']} minute values; linear interpolation share {_pct(nd['linear_share'])}",
        f"- METs column missing in {len(audit['wearable']['mets_column_missing'])} files "
        f"({audit['wearable']['mets_column_missing']})",
        "",
        _table(
            [
                "Target group (prediabetes + T2D)",
                "Participants",
                "Usable meals",
                "Positives",
                "Rate",
                "With ≥ 1 positive",
                "Viability rule",
            ],
            [
                [
                    "Frozen definition",
                    tf["participants"],
                    tf["usable_meals"],
                    tf["positives"],
                    _pct(tf["positive_rate"]),
                    tf["participants_with_positive"],
                    "pass" if tf["viability_pass"] else "FAIL",
                ],
                [
                    "After added exclusions (training/evaluation set)",
                    te["participants"],
                    te["usable_meals"],
                    te["positives"],
                    _pct(te["positive_rate"]),
                    te["participants_with_positive"],
                    "pass" if te["viability_pass"] else "FAIL",
                ],
            ],
        ),
        "",
        _table(
            ["Exclusion (first reason, in order)", "Meals"],
            [[k, v] for k, v in o["exclusion_waterfall"].items()],
        ),
    ]
    if audit["issues"]:
        lines += [
            "",
            "**Open issues:**",
            *[f"- {i['level']}: {i['issue']}" for i in audit["issues"]],
        ]
    return "\n".join(lines)


def full_markdown(audit: dict[str, Any], reconciliation: list[dict[str, Any]] | None) -> str:
    o, prov = audit["outcomes"], audit["provenance"]
    parts = [
        "# M1 data audit — CGMacros v1.0.0",
        "",
        "Generated by `make m1` from the source files. Every number is computed, none typed in.",
        "",
        "## Provenance",
        "",
        _table(
            ["Item", "Value"],
            [[k, v] for k, v in prov.items() if not isinstance(v, dict)]
            + [["official check", prov["official_check"]], ["pinned manifest", prov["lock_check"]]],
        ),
        "",
        "## Summary",
        "",
        summary_markdown(audit),
        "",
        "## By glycemic group (frozen definition)",
        "",
        _table(
            ["Group", "Participants", "Usable", "Positives", "Rate", "With ≥ 1 positive"],
            [
                [
                    g,
                    v["participants"],
                    v["usable_meals"],
                    v["positives"],
                    _pct(v["positive_rate"]),
                    v["participants_with_positive"],
                ]
                for g, v in o["frozen_by_group"].items()
            ],
        ),
        "",
        "## By glycemic group (training/evaluation set)",
        "",
        _table(
            ["Group", "Participants", "Eligible", "Positives", "Rate", "With ≥ 1 positive"],
            [
                [
                    g,
                    v["participants"],
                    v["usable_meals"],
                    v["positives"],
                    _pct(v["positive_rate"]),
                    v["participants_with_positive"],
                ]
                for g, v in o["eligible_by_group"].items()
            ],
        ),
        "",
        "## Exclusions (a meal can have several reasons)",
        "",
        _table(["Reason", "Meals"], [[k, v] for k, v in o["exclusion_counts_any"].items()]),
        "",
        f"Already high before the meal, among frozen-usable meals: "
        f"{o['already_high_among_frozen_usable']}",
        "",
        "## By participant",
        "",
        _table(
            [
                "ID",
                "Group",
                "Meals",
                "Frozen usable",
                "Frozen +",
                "Eligible",
                "Eligible +",
                "Already high",
            ],
            [
                [
                    r["participant_id"],
                    r["glycemic_group"],
                    r["meals"],
                    r["frozen_usable"],
                    r["frozen_positives"],
                    r["eligible"],
                    r["eligible_positives"],
                    r["already_high"],
                ]
                for r in o["by_participant"]
            ],
        ),
        "",
        "## Time series and native CGM grid",
        "",
        _table(
            [
                "ID",
                "Days",
                "Rows",
                "Dup. ts",
                "Gaps > 5 min",
                "Dexcom missing",
                "HR missing",
                "METs col",
                "Dexcom grid",
                "Phase(s)",
                "Native share",
                "Linear share",
            ],
            [
                [
                    s["participant_id"],
                    s["span_days"],
                    s["rows_after_dedup"],
                    s["duplicates"]["duplicated_timestamps"],
                    s["gaps_over_flag"],
                    _pct(s["missing_share"]["dexcom"]),
                    _pct(s["missing_share"]["hr"]),
                    "yes" if s["wearable"]["mets_available"] else "no",
                    s["native_grid"]["dexcom"]["decision"],
                    [
                        seg["phase"]
                        for seg in s["native_grid"]["dexcom"]["segments"]
                        if seg["status"] == "accepted"
                    ],
                    _pct(s["native_grid"]["dexcom"]["native_share"]),
                    _pct(s["native_grid"]["dexcom"]["linear_share"]),
                ]
                for s in audit["per_participant"]
            ],
        ),
        "",
        "## Wearable",
        "",
        "```json",
        dumps(audit["wearable"]).strip(),
        "```",
        "",
        "## Meals",
        "",
        "```json",
        dumps(audit["meals"]).strip(),
        "```",
        "",
        "## Schema",
        "",
        "```json",
        dumps(audit["schema"]).strip(),
        "```",
    ]
    if reconciliation is not None:
        parts += [
            "",
            "## Reconciliation with the Phase 0A exploratory audit",
            "",
            _table(
                ["Quantity", "Phase 0A", "M1", "Expected equal", "Match", "Note"],
                [
                    [
                        r["quantity"],
                        r["phase0a"]
                        if not isinstance(r["phase0a"], list)
                        else f"{len(r['phase0a'])} IDs",
                        r["m1"] if not isinstance(r["m1"], list) else f"{len(r['m1'])} IDs",
                        r["expected_equal"],
                        r["match"],
                        r["note"],
                    ]
                    for r in reconciliation
                ],
            ),
        ]
    parts += ["", "## Issues", ""]
    parts += [f"- **{i['level']}**: {i['issue']}" for i in audit["issues"]] or ["- none"]
    return "\n".join(parts) + "\n"


def update_data_card(card_path: Path, block: str) -> None:
    text = card_path.read_text()
    if AUTO_START not in text or AUTO_END not in text:
        raise ValueError(f"{card_path} is missing the AUTO:M1-AUDIT markers")
    head, rest = text.split(AUTO_START, 1)
    _, tail = rest.split(AUTO_END, 1)
    card_path.write_text(head + AUTO_START + "\n\n" + block.strip() + "\n\n" + AUTO_END + tail)
