from __future__ import annotations

import shutil
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent))
from fixture_data import write_fixture, zip_fixture  # noqa: E402

REPO = Path(__file__).resolve().parents[2]


@pytest.fixture(scope="session")
def dataset(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """The synthetic CGMacros-shaped folder (session-wide, read-only by convention)."""
    return write_fixture(tmp_path_factory.mktemp("src"))


@pytest.fixture(scope="session")
def dataset_zip(dataset: Path, tmp_path_factory: pytest.TempPathFactory) -> Path:
    return zip_fixture(dataset, tmp_path_factory.mktemp("zip") / "CGMacros_dateshifted365.zip")


@pytest.fixture
def repo_root(tmp_path: Path) -> Path:
    """A throwaway repo root holding the real configs and a data-card with AUTO markers."""
    root = tmp_path / "repo"
    (root / "data").mkdir(parents=True)
    shutil.copytree(REPO / "data/configs", root / "data/configs")
    (root / "docs").mkdir()
    (root / "docs/data-card.md").write_text(
        "# Card\n\nintro\n\n<!-- AUTO:M1-AUDIT START (generated by `make m1`; do not edit by hand) -->\n"
        "old\n<!-- AUTO:M1-AUDIT END -->\n\noutro\n"
    )
    return root
