"""M4 integration: the Digital Twin serves a real M3 model bundle, and computes exactly the inputs
M2/M3 trained on (no train/serve skew). SYNTHETIC fixtures only (fixture_data.py, m3_fixture.py).
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import pytest

sys.path.insert(0, str(Path(__file__).parent))
from m3_fixture import FIXTURE_LABEL, make_m2_like, pin_folds  # noqa: E402
from twin_core.features import as_ns  # noqa: E402
from twin_core.personalization import PopulationPrior, personal_features  # noqa: E402
from twin_core.twin import (  # noqa: E402
    InMemorySource,
    ModelContractError,
    PatientRecord,
    TwinConfigs,
    TwinRuntime,
    build_state,
    build_support_profile,
    simulate,
)
from twin_core.twin.record import clinical_from_row  # noqa: E402
from twin_ml.dataset.build import clinical_for  # noqa: E402
from twin_ml.dataset.run import run_m2  # noqa: E402
from twin_ml.pipeline.run import content_sha256, run_m1  # noqa: E402
from twin_ml.training.run import run_m3  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
CFG = TwinConfigs.load(REPO / "data/configs")
PRIOR = PopulationPrior(2.0, 3.0, (25.0, 1.1, -0.8, 0.05), 3.0, 30, 600)
FAST = {
    "primary_model": "logistic",
    "evaluation": {"bootstrap_resamples": 10, "ci": 0.95, "calibration_bins": 5},
}


@pytest.fixture(scope="module")
def m1m2(tmp_path_factory: pytest.TempPathFactory) -> tuple[dict[str, pd.DataFrame], pd.DataFrame]:
    from fixture_data import write_fixture

    src = write_fixture(tmp_path_factory.mktemp("src"))
    root = tmp_path_factory.mktemp("repo")
    (root / "data").mkdir()
    shutil.copytree(REPO / "data/configs", root / "data/configs")
    (root / "docs").mkdir()
    (root / "docs/data-card.md").write_text(
        "x\n<!-- AUTO:M1-AUDIT START (generated by `make m1`; do not edit by hand) -->\n"
        "<!-- AUTO:M1-AUDIT END -->\n"
    )
    tables = run_m1(src, root, write_outputs=False).tables
    return tables, run_m2(tables, root, write_outputs=False).dataset


@pytest.fixture(scope="module")
def bundle(tmp_path_factory: pytest.TempPathFactory) -> Any:
    data = make_m2_like()
    root = tmp_path_factory.mktemp("m3")
    shutil.copytree(REPO / "data/configs", root / "data/configs")
    pin_folds(data, root)
    res = run_m3(
        data,
        root,
        write_outputs=False,
        dataset_label=FIXTURE_LABEL,
        overrides=FAST,
        require_xgboost=False,
    )
    return res.bundles["logistic__full_personal"], data


def records(tables: dict[str, pd.DataFrame]) -> InMemorySource:
    pids = sorted(tables["meals"]["participant_id"].unique())
    return InMemorySource(
        {int(p): PatientRecord.from_m1_tables(tables, int(p), "SYNTHETIC M1 FIXTURE") for p in pids}
    )


class FixedPriorModel:
    """Captures the twin's model input row; carries a fixed prior (SYNTHETIC)."""

    def __init__(self) -> None:
        self.columns = CFG.contract.columns(CFG.features)
        self.feature_set = "full_personal"
        self.model_name = "capture"
        self.contract_version = CFG.contract.version
        self.contract_sha256 = CFG.hashes["model_contract"]
        self.features_sha256 = CFG.hashes["features"]
        self.labels_sha256 = CFG.hashes["labels"]
        self.threshold = 0.5
        self.prior = PRIOR
        self.rows: list[pd.DataFrame] = []

    def predict_proba(self, X: pd.DataFrame) -> np.ndarray:
        self.rows.append(X.copy())
        return np.full(len(X), 0.5)


def test_clinical_encoding_matches_training(m1m2: Any) -> None:
    tables, _ = m1m2
    for _, row in tables["clinical_wide"].iterrows():
        a, b = clinical_from_row(row.to_dict()), clinical_for(row)
        assert {k: a[k] for k in b} == pytest.approx(b, nan_ok=True)


def test_no_train_serve_skew_for_any_meal(m1m2: Any) -> None:
    """For every meal, the twin's 45 inputs equal the M2 base features plus the personal features
    M3 computes with the same prior."""
    tables, dataset = m1m2
    src = records(tables)
    model = FixedPriorModel()
    rt = TwinRuntime(CFG, model)  # type: ignore[arg-type]
    base_cols = list(CFG.contract.columns(CFG.features, "full_multimodal"))
    personal = pd.concat(
        personal_features(g, PRIOR, CFG.labels.horizon_min)
        for _, g in dataset.groupby("participant_id")
    ).loc[dataset.index]
    checked = 0
    for i, row in dataset.iterrows():
        t0 = pd.Timestamp(row["started_at"])
        s = build_state(
            int(row["participant_id"]),
            t0,
            source=src,
            runtime=rt,
            current_meal_id=str(row["meal_id"]),
        )
        inputs = s.risk.model_inputs
        assert inputs is not None and list(inputs) == list(model.columns)
        served = np.array([np.nan if inputs[c] is None else inputs[c] for c in base_cols], float)
        np.testing.assert_allclose(
            served,
            row[base_cols].to_numpy(float),
            equal_nan=True,
            err_msg=f"base features differ for {row['meal_id']}",
        )
        for c in ("p_personal", "rise_offset_mgdl", "personal_weight"):
            assert inputs[c] == pytest.approx(personal.loc[i, c]), (row["meal_id"], c)
        checked += 1
    assert checked == len(dataset) == 40


def test_twin_serves_a_real_m3_bundle(m1m2: Any, bundle: Any) -> None:
    tables, _ = m1m2
    b, _ = bundle
    rt = TwinRuntime(CFG, b)
    src = records(tables)
    meals = tables["meals"]
    ok = (
        tables["meal_outcomes"]
        .query("eligible")
        .merge(meals[["meal_id", "started_at"]], on="meal_id")
    )
    m = ok.iloc[0]
    s = build_state(
        int(m["participant_id"]),
        m["started_at"] + pd.Timedelta(minutes=10),
        source=src,
        runtime=rt,
        current_meal_id=m["meal_id"],
    )
    assert s.risk.status == "scored" and s.risk.probability is not None
    X = pd.DataFrame([s.risk.model_inputs]).astype(float)
    assert s.risk.probability == pytest.approx(float(b.predict_proba(X)[0]))
    assert s.risk.threshold == b.threshold
    ident = s.provenance.model
    assert ident is not None and ident.contract_sha256 == b.contract_sha256
    assert ident.dataset_content_sha256 == b.dataset_content_sha256
    assert ident.model_name == "logistic" and ident.feature_set == "full_personal"
    assert s.personal_response is not None
    assert s.personal_response.prior_fitted_on_people == b.prior.n_people  # the bundle's own prior


def test_support_profile_is_tied_to_the_bundles_training_data(m1m2: Any, bundle: Any) -> None:
    tables, m2 = m1m2
    b, train_data = bundle
    cols = CFG.contract.columns(CFG.features)
    wrong = build_support_profile(m2, cols, (0.01, 0.99), content_sha256(m2))
    with pytest.raises(ModelContractError, match="different training dataset"):
        TwinRuntime(CFG, b, wrong)
    right = build_support_profile(train_data, cols, (0.01, 0.99), content_sha256(train_data))
    assert right.dataset_content_sha256 == b.dataset_content_sha256
    rt = TwinRuntime(CFG, b, right)
    assert "p_personal" not in right.features and "carbs_g" in right.features
    src = records(tables)
    meals = tables["meals"]
    ok = (
        tables["meal_outcomes"]
        .query("eligible")
        .merge(meals[["meal_id", "started_at"]], on="meal_id")
    )
    m = ok.iloc[0]
    r = simulate(
        int(m["participant_id"]),
        m["started_at"],
        {"carbs_g": -10},
        source=src,
        runtime=rt,
        current_meal_id=m["meal_id"],
    )
    assert r.status in ("ok", "out_of_support") and r.model.model_version.startswith("logistic__")


def test_proposed_meal_is_scored_like_a_logged_one(m1m2: Any) -> None:
    tables, _ = m1m2
    src = records(tables)
    model = FixedPriorModel()
    rt = TwinRuntime(CFG, model)  # type: ignore[arg-type]
    row = tables["meals"].query("macro_validity == 'valid'").iloc[3]
    from twin_core.features import meal_input

    logged = build_state(
        int(row["participant_id"]),
        row["started_at"],
        source=src,
        runtime=rt,
        current_meal_id=row["meal_id"],
    )
    proposed_meal = meal_input(row.to_dict())
    assert as_ns(proposed_meal.started_at) == as_ns(row["started_at"])
    # a proposed meal at the same time: drop the logged one from the record first
    rec = src.record(int(row["participant_id"]))
    without = PatientRecord(
        rec.patient_id,
        rec.clinical,
        rec.cgm,
        rec.wearable,
        rec.meals[rec.meals["meal_id"] != row["meal_id"]],
        rec.glycemic_group,
        rec.source,
    )
    proposed = build_state(
        rec.patient_id,
        row["started_at"],
        source=InMemorySource({rec.patient_id: without}),
        runtime=rt,
        current_meal=proposed_meal,
    )
    assert proposed.risk.model_inputs == logged.risk.model_inputs


def test_xgboost_bundle_is_served_when_available(m1m2: Any, tmp_path: Path) -> None:
    pytest.importorskip("xgboost")
    data = make_m2_like()
    shutil.copytree(REPO / "data/configs", tmp_path / "data/configs")
    pin_folds(data, tmp_path)
    res = run_m3(
        data,
        tmp_path,
        write_outputs=False,
        dataset_label=FIXTURE_LABEL,
        overrides={"evaluation": FAST["evaluation"]},
    )
    b = res.bundles["xgboost__full_personal"]
    tables, _ = m1m2
    meals = tables["meals"]
    ok = (
        tables["meal_outcomes"]
        .query("eligible")
        .merge(meals[["meal_id", "started_at"]], on="meal_id")
    )
    m = ok.iloc[0]
    s = build_state(
        int(m["participant_id"]),
        m["started_at"],
        source=records(tables),
        runtime=TwinRuntime(CFG, b),
        current_meal_id=m["meal_id"],
    )
    assert s.risk.status == "scored" and s.provenance.model is not None
    assert s.provenance.model.model_name == "xgboost"
